monitor: val_loss
monitor_mode: min
seed_everything: 128

model:
  class_path: src.classplusseq.model.LightningModule
  init_args:
    arch: seresnext50_32x4d.racm_in1k
    emb_dim: 128
    n_heads: 4
    n_layers: 4
    att_dropout: 0.1
    linear_dropout: 0.1
    optimizer:
      class_path: torch.optim.Adam
      init_args:
        lr: 1.0
    lr_scheduler:
      class_path: torch.optim.lr_scheduler.CyclicLR
      init_args:
        base_lr: 1e-7
        max_lr: 1e-4
        step_size_up: 150
        step_size_down: 200
        mode: exp_range
        gamma: 0.999
    interval: step

data:
  class_path: src.classplusseq.data_loading.DataModule
  init_args:
    img_dir: data/train_images_clip
    batch_size: 16
    img_size: 32

trainer:
  accumulate_grad_batches: 2
  logger:
    class_path: src.callbacks.CustomLogger
    init_args:
      save_dir: lightning_logs/
      name: ""
      train_c: train_loss_epoch
      val_c: val_loss
  enable_checkpointing: true
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: ${monitor}
        patience: 5
        mode: ${monitor_mode}
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: ${monitor}
        mode: ${monitor_mode}
        filename: '{epoch}_{${monitor}:.4f}'
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
  accelerator: gpu
  precision: 16-mixed
  max_epochs: 10000

ckpt_path: null
