monitor: val_loss
monitor_mode: min
seed_everything: 128


model:
  class_path: src.e2e.model.LightningModule
  init_args:
    arch: densenet201
    emb_dim: 8
    n_heads: 2
    n_layers: 2
    att_dropout: 0.1
    linear_dropout: 0.1
    optimizer:
      class_path: torch.optim.Adam
      init_args:
        lr: 1.0
    lr_scheduler:
      class_path: torch.optim.lr_scheduler.CyclicLR
      init_args:
        base_lr: 1e-7
        max_lr: 1e-4
        step_size_up: 150
        step_size_down: 200
        mode: exp_range
        gamma: 0.999
    interval: step

data:
  class_path: src.e2e.data_loading.DataModule
  init_args:
    img_dir: data/train_images_natural_v2
    batch_size: 4
    img_size: 260
    meta_path: data/metadata_v4_norm.csv

trainer:
  accumulate_grad_batches: 8
  logger:
    class_path: CSVLogger
    init_args:
      save_dir: lightning_logs/
      name: ""
  enable_checkpointing: true
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: ${monitor}
        patience: 3
        mode: ${monitor_mode}
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: ${monitor}
        mode: ${monitor_mode}
        filename: '{epoch}_{${monitor}:.4f}'
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
    # - class_path: src.finetuning.CustomBackboneFinetuning
    #   init_args:
    #     unfreeze_backbone_at_epoch: 1
    #     backbone_initial_ratio_lr: 1
    #     multiplicative: 1
    #     verbose: True
    #     should_align: True
    #     train_bn: True
  log_every_n_steps: 1
  accelerator: gpu
  precision: 16-mixed
  max_epochs: 10000

ckpt_path: null
