monitor: val_loss
monitor_mode: min
seed_everything: 128

optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 1e-04

lr_scheduler:
  class_path: lightning.pytorch.cli.ReduceLROnPlateau
  init_args:
    factor: 0.1
    patience: 1
    monitor: ${monitor}
    mode: ${monitor_mode}

model:
  class_path: src.e2e.model.LightningModule
  init_args:
    arch: tf_efficientnet_b2.ns_jft_in1k
    emb_dim: 128
    n_heads: 4
    n_layers: 2
    att_dropout: 0.1
    linear_dropout: 0.1

data:
  class_path: src.e2e.data_loading.DataModule
  init_args:
    img_dir: data/train_images_260
    batch_size: 8
    img_size: 260

trainer:
  logger:
    class_path: CSVLogger
    init_args:
      save_dir: lightning_logs/
      name: ""
  enable_checkpointing: true
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: ${monitor}
        patience: 3
        mode: ${monitor_mode}
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: ${monitor}
        mode: ${monitor_mode}
        filename: '{epoch}_{${monitor}:.4f}'
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
    # - class_path: src.finetuning.CustomBackboneFinetuning
    #   init_args:
    #     unfreeze_backbone_at_epoch: 1
    #     backbone_initial_ratio_lr: 1
    #     multiplicative: 1
    #     verbose: True
    #     should_align: True
    #     train_bn: True
  log_every_n_steps: 10
  accelerator: gpu
  precision: 16-mixed
  accumulate_grad_batches: 2
  max_epochs: 10000

ckpt_path: null
