monitor: val_loss
monitor_mode: min
seed_everything: 128

optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 1e-04

model:
  class_path: src.image.model.LightningModule
  init_args:
    arch: tf_efficientnet_b4.ns_jft_in1k


data:
  class_path: src.image.data_loading.DataModule
  init_args:
    img_size: 380
    batch_size: 64
    img_dir: data/train_images_380

trainer:
  logger:
  enable_checkpointing: true
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: ${monitor}
        patience: 1
        mode: ${monitor_mode}
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: ${monitor}
        mode: ${monitor_mode}
        filename: '{epoch}_{${monitor}:.4f}'
    - class_path: src.image.writer.Writer

  accelerator: gpu
  precision: 16-mixed
  benchmark: True
  accumulate_grad_batches: 1
  max_epochs: 10000



ckpt_path: null
