monitor: val_loss
monitor_mode: min
seed_everything: 128

model:
  class_path: src.image.model.LightningModule
  init_args:
    arch: densenet201
    dropout: 0.3
    optimizer:
      class_path: torch.optim.Adam
      init_args:
        lr: 1.0
    lr_scheduler:
      class_path: torch.optim.lr_scheduler.OneCycleLR
      init_args:
        max_lr: 1e-4
        epochs: 16
        steps_per_epoch: 614
        pct_start: 0.125
        div_factor: 1000
        final_div_factor: 50
    interval: step

data:
  class_path: src.image.data_loading.DataModule
  init_args:
    img_size: 380
    batch_size: 32
    img_dir: data/train_images_natural

trainer:
  logger:
    class_path: CSVLogger
    init_args:
      save_dir: lightning_logs/
      name: ""
  enable_checkpointing: true
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: ${monitor}
        patience: 2
        mode: ${monitor_mode}
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: ${monitor}
        mode: ${monitor_mode}
        filename: '{epoch}_{${monitor}:.4f}'
    - class_path: src.image.writer.Writer
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch

  accelerator: gpu
  precision: 16-mixed
  benchmark: True
  accumulate_grad_batches: 1
  max_epochs: 10000

ckpt_path: null
