monitor: val_loss
monitor_mode: min
seed_everything: 128

model:
  class_path: src.levels.model.LightningModule
  init_args:
    arch: regnetz_b16.ra3_in1k
    pretrained: true
    eval: false
    dropout: 0.3
    emb_dim: 512
    optimizer:
      class_path: torch.optim.Adam
      init_args:
        lr: 1e-4
    lr_scheduler:
      class_path: src.model.WarmupLR
      init_args:
        warmup_steps: 342
    interval: step

data:
  class_path: src.levels.data_loading.DataModule
  init_args:
    img_size: 448
    batch_size: 32
    img_dir: mount/train_images_clip
    num_workers: 6

trainer:
  logger:
    class_path: src.callbacks.CustomLogger
    init_args:
      save_dir: lightning_logs/
      name: ""
      train_c: train_loss
      val_c: val_loss
  enable_checkpointing: true
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: ${monitor}
        patience: 3
        mode: ${monitor_mode}
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: ${monitor}
        mode: ${monitor_mode}
        filename: '{epoch}_{${monitor}:.4f}'
    - class_path: src.callbacks.Writer
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: src.callbacks.CustomBackboneFinetuning
      init_args:
        unfreeze_at_epoch: 0
        unfreeze_bn: true
        backbone_names:
        - backbone

  accelerator: gpu
  precision: 16-mixed
  benchmark: True
  accumulate_grad_batches: 1
  max_epochs: 10000

ckpt_path: null
