monitor: val_loss
monitor_mode: min
seed_everything: 128

model:
  class_path: src.patch.model.LightningModule
  init_args:
    arch: seresnext50_32x4d.racm_in1k
    eval: True
    pretrained: True
    do_any_severe_spinal: False
    linear_dropout: 0.3
    optimizer:
      class_path: torch.optim.Adam
      init_args:
        lr: 1e-4
    lr_scheduler:
      class_path: src.model.WarmupLR
      init_args:
        warmup_steps: 304
    interval: step

data:
  class_path: src.patch.data_loading.DataModule
  init_args:
    img_dir: mount/train_images_clip
    batch_size: 128
    img_size: 112
    size_ratio: 10

trainer:
  accumulate_grad_batches: 1
  logger:
    class_path: src.callbacks.CustomLogger
    init_args:
      save_dir: lightning_logs/
      name: ""
      train_c: train_loss_epoch
      val_c: val_loss
  enable_checkpointing: true
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: ${monitor}
        patience: 5
        mode: ${monitor_mode}
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: ${monitor}
        mode: ${monitor_mode}
        filename: '{epoch}_{${monitor}:.4f}'
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: src.callbacks.Writer
    # - class_path: src.callbacks.CustomBackboneFinetuning
    #   init_args:
    #     unfreeze_at_epoch: 5
    #     unfreeze_bn: True
  accelerator: gpu
  precision: 16-mixed
  max_epochs: 10000

ckpt_path: null
