monitor: val_loss
monitor_mode: min
seed_everything: 128

model:
  class_path: src.patchseq.model.LightningModule
  init_args:
    arch: tinynet_a
    emb_dim: 128
    n_heads: 4
    n_layers: 4
    att_dropout: 0.1
    linear_dropout: 0.1
    optimizer:
      class_path: torch.optim.Adam
      init_args:
        lr: 1e-7
    lr_scheduler:
      class_path: torch.optim.lr_scheduler.CyclicLR
      init_args:
        base_lr: 1e-7
        max_lr: 1e-4
        step_size_up: 394
        step_size_down: 591
        mode: exp_range
        gamma: 0.999
    interval: step

data:
  class_path: src.patchseq.data_loading.DataModule
  init_args:
    img_dir: data/train_images_clip
    batch_size: 8
    img_size: 64

trainer:
  accumulate_grad_batches: 1
  logger:
    class_path: src.callbacks.CustomLogger
    init_args:
      save_dir: lightning_logs/
      name: ""
      train_c: train_loss_epoch
      val_c: val_loss
  enable_checkpointing: true
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: ${monitor}
        patience: 11
        mode: ${monitor_mode}
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: ${monitor}
        mode: ${monitor_mode}
        filename: '{epoch}_{${monitor}:.4f}'
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
    # - class_path: src.finetuning.CustomBackboneFinetuning
    #   init_args:
    #     unfreeze_backbone_at_epoch: 3
    #     backbone_initial_ratio_lr: 1
    #     multiplicative: 1
    #     verbose: True
    #     should_align: True
    #     train_bn: True
  accelerator: gpu
  precision: 16-mixed
  max_epochs: 10000

ckpt_path: null
