monitor: val_loss
monitor_mode: min
seed_everything: 128

model:
  class_path: src.patchseq.model.LightningModule
  init_args:
    arch: mobilenetv4_conv_small
    eval: true
    pretrained: True
    emb_dim: 512
    n_heads: 4
    n_layers: 6
    att_dropout: 0.1
    linear_dropout: 0.2
    optimizer:
      class_path: torch.optim.Adam
      init_args:
        lr: 1e-4
    lr_scheduler:
      class_path: src.model.WarmupLR
      init_args:
        warmup_steps: 493
    interval: step

data:
  class_path: src.patchseq.data_loading.DataModule
  init_args:
    img_dir: data/train_images_clip
    batch_size: 16
    img_size: 112
    size_ratio: 10

trainer:
  accumulate_grad_batches: 1
  logger:
    class_path: src.callbacks.CustomLogger
    init_args:
      save_dir: lightning_logs/
      name: ""
      train_c: train_loss_epoch
      val_c: val_loss
  enable_checkpointing: true
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: ${monitor}
        patience: 5
        mode: ${monitor_mode}
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: ${monitor}
        mode: ${monitor_mode}
        filename: '{epoch}_{${monitor}:.4f}'
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
    # - class_path: src.finetuning.CustomBackboneFinetuning
    #   init_args:
    #     unfreeze_at_epoch: 5
    #     unfreeze_bn: True
  accelerator: gpu
  precision: 16-mixed
  max_epochs: 10000

ckpt_path: null
