monitor: val_loss
monitor_mode: min
seed_everything: 128

model:
  class_path: src.probas.model.LightningModule
  init_args:
    linear_dropout: 0.5
    optimizer:
      class_path: torch.optim.Adam
      init_args:
        lr: 8.0e-06
    lr_scheduler:
      class_path: torch.optim.lr_scheduler.CyclicLR
      init_args:
        base_lr: 8.0e-06
        max_lr: 3.0e-3
        step_size_up: 98
        step_size_down: 147
        mode: exp_range
        gamma: 0.999
    interval: step

data:
  class_path: src.probas.data_loading.DataModule
  init_args:
    batch_size: 32

trainer:
  accumulate_grad_batches: 1
  logger:
    class_path: src.callbacks.CustomLogger
    init_args:
      save_dir: lightning_logs/
      name: ""
      train_c: train_loss_epoch
      val_c: val_loss
  enable_checkpointing: true
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: ${monitor}
        patience: 10
        mode: ${monitor_mode}
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: ${monitor}
        mode: ${monitor_mode}
        filename: '{epoch}_{${monitor}:.4f}'
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: src.callbacks.Writer
    # - class_path: src.finetuning.CustomBackboneFinetuning
    #   init_args:
    #     unfreeze_at_epoch: 5
    #     unfreeze_bn: True
  accelerator: gpu
  precision: 16-mixed
  max_epochs: 10000

ckpt_path: null
