monitor: val_loss
monitor_mode: min
seed_everything: 128

model:
  class_path: src.segmentation.model.LightningModule
  init_args:
    arch: unetplusplus
    encoder_name: tu-densenet201
    encoder_weights: imagenet
    optimizer:
      class_path: torch.optim.Adam
      init_args:
        lr: 1.0
    lr_scheduler:
      class_path: torch.optim.lr_scheduler.OneCycleLR
      init_args:
        max_lr: 1e-4
        epochs: 15
        steps_per_epoch: 614
        pct_start: 0.2
        div_factor: 1000
        final_div_factor: 500
    interval: step

data:
  class_path: src.segmentation.data_loading.DataModule
  init_args:
    img_size: 384
    batch_size: 16
    img_dir: data/train_images_natural_v2

trainer:
  accumulate_grad_batches: 2
  logger:
    class_path: CSVLogger
    init_args:
      save_dir: lightning_logs/
      name: ""
  enable_checkpointing: true
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: ${monitor}
        patience: 2
        mode: ${monitor_mode}
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: ${monitor}
        mode: ${monitor_mode}
        filename: '{epoch}_{${monitor}:.4f}'
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch

  accelerator: gpu
  precision: 16-mixed
  benchmark: True
  max_epochs: 10000

ckpt_path: null
