monitor: val_loss
monitor_mode: min
seed_everything: 128

data:
  class_path: src.sequence.data_loading.DataModule
  init_args:
    batch_size: 16
    aug: 0.1
    feats_path: lightning_logs/version_1/preds.parquet
    meta_path: data/metadata_v4_norm.csv
    levels_path: lightning_logs/version_3/preds.parquet

model:
  class_path: src.sequence.model.LightningModule
  init_args:
    emb_dim: 256
    n_heads: 4
    n_layers: 4
    att_dropout: 0.2
    linear_dropout: 0.2
    optimizer:
      class_path: torch.optim.Adam
      init_args:
        lr: 5e-4
    lr_scheduler:
      class_path: src.model.WarmupLR
      init_args:
        warmup_steps: 192
    interval: step

trainer:
  logger:
    class_path: src.callbacks.CustomLogger
    init_args:
      save_dir: lightning_logs/
      name: ""
  enable_checkpointing: true
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: ${monitor}
        patience: 10
        mode: ${monitor_mode}
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: ${monitor}
        mode: ${monitor_mode}
        filename: '{epoch}_{${monitor}:.4f}'
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
  accelerator: gpu
  precision: 16-mixed
  accumulate_grad_batches: 1
  max_epochs: 10000

ckpt_path: null
