monitor: val_loss
monitor_mode: min
seed_everything: 128

model:
  class_path: src.sequence.model.LightningModule
  init_args:
    # ckpt_path: lightning_logs/version_8/checkpoints/epoch=1_val_loss=0.4374.ckpt
    image:
      ckpt_path: checkpoints/patch/checkpoints/epoch=7_val_loss=0.4561.ckpt
      arch: regnetz_b16.ra3_in1k
      eval: True
      pretrained: True
    train_any_severe_spinal: False
    emb_dim: 768
    n_heads: 4
    n_layers: 6
    att_dropout: 0.1
    emb_dropout: 0.1
    out_dropout: 0.3
    add_mid_transformer: False
    optimizer:
      class_path: torch.optim.Adam
      init_args:
        lr: 1e-4
    lr_scheduler:
      class_path: src.model.WarmupLR
      init_args:
        warmup_steps: 493
    interval: step

data:
  class_path: src.sequence.data_loading.DataModule
  init_args:
    img_dir: mount/train_images_clip
    batch_size: 16
    img_size: 112
    size_ratio: 9
    train_per_level: True

trainer:
  accumulate_grad_batches: 1
  logger:
    class_path: src.callbacks.CustomLogger
    init_args:
      save_dir: lightning_logs/
      name: ""
      train_c: train_loss_epoch
      val_c: val_loss
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: ${monitor}
        patience: 5
        mode: ${monitor_mode}
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: ${monitor}
        mode: ${monitor_mode}
        filename: '{epoch}_{${monitor}:.4f}'
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: src.callbacks.Writer
    - class_path: src.callbacks.CustomBackboneFinetuning
      init_args:
        unfreeze_at_epoch: -1
        unfreeze_bn: False
  accelerator: gpu
  precision: 16-mixed
  max_epochs: 10000

ckpt_path: null
