monitor: val_loss
monitor_mode: min
seed_everything: 128

data:
  class_path: src.sequence.data_loading.DataModule
  init_args:
    batch_size: 32
    aug: 0.1
    feats_path: data/feats_densenet200_7.parquet
    meta_path: data/metadata_v4_norm.csv

model:
  class_path: src.sequence.model.LightningModule
  init_args:
    emb_dim: 256
    n_heads: 8
    n_layers: 4
    att_dropout: 0.2
    linear_dropout: 0.2
    optimizer:
      class_path: torch.optim.Adam
      init_args:
        lr: 1.0
    lr_scheduler:
      class_path: torch.optim.lr_scheduler.CyclicLR
      init_args:
        base_lr: 1.0e-05
        max_lr: 3.0e-3
        step_size_up: 98
        step_size_down: 147
        mode: exp_range
        gamma: 0.999
    interval: step

trainer:
  logger:
    class_path: CSVLogger
    init_args:
      save_dir: lightning_logs/
      name: ""
  enable_checkpointing: true
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: ${monitor}
        patience: 10
        mode: ${monitor_mode}
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: ${monitor}
        mode: ${monitor_mode}
        filename: '{epoch}_{${monitor}:.4f}'
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
  accelerator: gpu
  precision: 16-mixed
  accumulate_grad_batches: 1
  max_epochs: 10000

ckpt_path: null
