monitor: val_loss
monitor_mode: min
seed_everything: 128

optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 1e-03

lr_scheduler:
  class_path: ReduceLROnPlateau
  init_args:
    factor: 0.1
    patience: 1
    monitor: ${monitor}
    mode: ${monitor_mode}
    verbose: True

model:
  class_path: src.sequence.model.LightningModule
  init_args:
    emb_dim: 16
    lstms: 2
    dropout: 0.3

trainer:
  logger:
    class_path: CSVLogger
    init_args:
      save_dir: lightning_logs/
      name: ""
  enable_checkpointing: true
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: ${monitor}
        patience: 2
        mode: ${monitor_mode}
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: ${monitor}
        mode: ${monitor_mode}
        filename: '{epoch}_{${monitor}:.4f}'
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch

  accelerator: gpu
  precision: 16-mixed
  # benchmark: True
  accumulate_grad_batches: 2
  max_epochs: 10000

data:
  class_path: src.sequence.data_loading.DataModule
  init_args:
    batch_size: 32

ckpt_path: null
