monitor: val_loss
monitor_mode: min
seed_everything: 128

data:
  class_path: src.sequence.data_loading.DataModule
  init_args:
    batch_size: 32
    feats_path: data/preds_densenet200/feats.parquet

model:
  class_path: src.sequence.model.LightningModule
  init_args:
    emb_dim: 64
    n_heads: 1
    n_layers: 4
    att_dropout: 0.1
    linear_dropout: 0.1
    optimizer:
      class_path: torch.optim.Adam
      init_args:
        lr: 1.0
    lr_scheduler:
      class_path: torch.optim.lr_scheduler.OneCycleLR
      init_args:
        max_lr: 1e-2
        epochs: 25
        steps_per_epoch: 25
        pct_start: 0.08
        div_factor: 500
        final_div_factor: 1000
    interval: step


trainer:
  logger:
    class_path: CSVLogger
    init_args:
      save_dir: lightning_logs/
      name: ""
  enable_checkpointing: true
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: ${monitor}
        patience: 4
        mode: ${monitor_mode}
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: ${monitor}
        mode: ${monitor_mode}
        filename: '{epoch}_{${monitor}:.4f}'
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
  log_every_n_steps: 10

  accelerator: gpu
  precision: 16-mixed
  # benchmark: True
  accumulate_grad_batches: 2
  max_epochs: 10000

ckpt_path: null
