from src import constants


N_IMG_ENSEMBLES = 5

M = 103
D = 8

N_LEVEL = len(constants.LEVELS)
N_CONDITION_LEVEL = len(constants.CONDITION_LEVEL)
N_SEVERITY = len(constants.SEVERITY2LABEL) + 1
N_CONDITION = len(constants.CONDITIONS_COMPLETE)


F = 1920
SIMILARITY_DIM = 8

INPUT_SIZE = (F + N_CONDITION * N_LEVEL * SIMILARITY_DIM  + N_CONDITION_LEVEL * N_SEVERITY) * N_IMG_ENSEMBLES + M + D
