from src import constants


N_IMG_ENSEMBLES = 5

M = 103
P = len(constants.DESCRIPTIONS)

N_LEVEL = len(constants.LEVELS)
N_CONDITION_LEVEL = len(constants.CONDITION_LEVEL)
N_SEVERITY = len(constants.SEVERITY2LABEL) + 1
N_CONDITION = len(constants.CONDITIONS_COMPLETE)
XY = 3

F = 1920
SIMILARITY_DIM = 32

IMG_O1 = N_LEVEL * SIMILARITY_DIM
IMG_O2 = N_CONDITION_LEVEL * XY
IMG_O3 = N_CONDITION_LEVEL * N_SEVERITY

INPUT_SIZE = (F + IMG_O1 + IMG_O2 + IMG_O3 + P) * N_IMG_ENSEMBLES + M + P
